name: A workflow for my goodbye world file
on: push

jobs:
  build:
    name: Goodbye world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./action-a
        env:
          MY_NAME: "Lars Schou"
